/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Index */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user info. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserContainerResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe - checks if the application can serve traffic.
         * @description Verifies that all dependencies (database) are accessible.
         *     Use this for load balancer health checks that should remove
         *     unhealthy instances from the pool.
         *
         *     Returns:
         *     200: Application is ready to serve traffic
         *     503: Application is not ready (dependency failure)
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReadinessResponse"];
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HTTPError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available models. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ModelsListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe - checks if the application process is running.
         * @description This endpoint should NOT check external dependencies (database, APIs).
         *     It only verifies the Flask application is responding to requests.
         *
         *     Use /api/ready for readiness checks that verify dependencies.
         *
         *     Returns:
         *     200: Application is alive and responding
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current app version (JS bundle hash).
         * @description This endpoint does not require authentication so version can be
         *     checked even before login. Used by frontend to detect when a new
         *     version is deployed and prompt users to reload.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VersionResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate with Google ID token from Sign In with Google. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HTTPError"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HTTPError"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HTTPError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Static Files */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    path: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HTTPError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all memories for the current user. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MemoriesListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh the JWT token.
         * @description Returns a new token with extended expiration.
         *     The old token remains valid until its original expiration.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenRefreshResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/client-id": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return Google Client ID for frontend initialization. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClientIdResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List conversations for the current user with pagination.
         * @description Query parameters:
         *     - limit: Number of conversations to return (default: 30, max: 100)
         *     - cursor: Cursor from previous page for fetching next page
         *
         *     Returns paginated conversations with message_count for proper sync initialization.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConversationsListPaginatedResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Create a new conversation. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConversationResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get file upload configuration for frontend. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UploadConfigResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user settings including custom instructions. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserSettingsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update user settings. */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StatusResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/conversations/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sync conversations - returns conversations updated since a given timestamp.
         * @description Query parameters:
         *     - since: ISO timestamp to get conversations updated after this time (optional)
         *     - full: If "true", returns all conversations for delete detection (optional)
         *
         *     Returns:
         *     - conversations: List of conversation objects with message_count
         *     - server_time: Current server timestamp to use for next sync
         *     - is_full_sync: Whether this was a full sync (all conversations returned)
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SyncResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memories/{memory_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a memory. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    memory_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StatusResponse"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HTTPError"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/messages/{message_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a message.
         * @description Deletes a single message and its associated files/thumbnails.
         *     The message must belong to a conversation owned by the authenticated user.
         *     Cost data is intentionally preserved for accurate reporting.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    message_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StatusResponse"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HTTPError"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/costs/monthly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get cost for the current user in a specific month. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MonthlyCostResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HTTPError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/costs/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get monthly cost history for the current user. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CostHistoryResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conv_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a conversation with its messages (paginated).
         * @description Query parameters for message pagination:
         *     - message_limit: Number of messages to return (default: 50, max: 200)
         *     - message_cursor: Cursor for fetching older/newer messages
         *     - direction: "older" (default) or "newer" for pagination direction
         *
         *     By default, returns the newest messages.
         *
         *     Optimized: Only includes file metadata, not thumbnails or full file data.
         *     Thumbnails are fetched on-demand via /api/messages/<message_id>/files/<file_index>/thumbnail.
         *     Full files can be fetched via /api/messages/<message_id>/files/<file_index>.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    conv_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConversationDetailPaginatedResponse"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HTTPError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete a conversation. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    conv_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StatusResponse"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HTTPError"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Update a conversation (title, model). */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    conv_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StatusResponse"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HTTPError"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/messages/{message_id}/cost": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get cost for a specific message. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    message_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MessageCostResponse"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HTTPError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conv_id}/cost": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get total cost for a conversation. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    conv_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConversationCostResponse"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HTTPError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conv_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get paginated messages for a conversation.
         * @description This is a dedicated endpoint for fetching message pages, more efficient
         *     than the full conversation endpoint when only messages are needed.
         *
         *     Query parameters:
         *     - limit: Number of messages to return (default: 50, max: 200)
         *     - cursor: Cursor for fetching older/newer messages
         *     - direction: "older" (default) or "newer" for pagination direction
         *
         *     By default, returns the newest messages.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    conv_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MessagesListResponse"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HTTPError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conv_id}/chat/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a message and get a complete response (non-streaming).
         * @description Accepts JSON body with:
         *     - message: str (optional if files present) - the text message
         *     - files: list[dict] (optional if message present) - array of {name, type, data} file objects
         *     - force_tools: list[str] (optional) - list of tool names to force (e.g. ["web_search"])
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    conv_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChatBatchResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HTTPError"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HTTPError"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HTTPError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conv_id}/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stream chat response via SSE
         * @description Send a message and stream the response via Server-Sent Events.
         *
         *     Returns text/event-stream with the following event types:
         *     - `thinking`: LLM thinking text (if enabled) - `{"type": "thinking", "text": "..."}`
         *     - `tool_start`: Tool starting - `{"type": "tool_start", "tool": "web_search", "detail": "..."}`
         *     - `tool_end`: Tool completed - `{"type": "tool_end", "tool": "web_search"}`
         *     - `token`: Content token - `{"type": "token", "text": "..."}`
         *     - `error`: Error occurred - `{"type": "error", "message": "...", "code": "...", "retryable": bool}`
         *     - `done`: Stream complete with metadata - `{"type": "done", "id": "...", "created_at": "...", ...}`
         *
         *     Uses SSE keepalive heartbeats (`: keepalive` comments) to prevent proxy timeouts.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    conv_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HTTPError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/messages/{message_id}/files/{file_index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get full file from a message
         * @description Returns the file as binary data with appropriate content-type header.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    message_id: string;
                    file_index: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HTTPError"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HTTPError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/messages/{message_id}/files/{file_index}/thumbnail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get thumbnail for an image file
         * @description Returns thumbnail binary data (200) or pending status (202).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    message_id: string;
                    file_index: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HTTPError"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HTTPError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * UserResponse
         * @description User information.
         */
        "UserContainerResponse.UserResponse": {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Name */
            name: string;
            /**
             * Picture
             * @default null
             */
            picture: string | null;
        };
        /**
         * UserContainerResponse
         * @description Response containing user info (used by /auth/me).
         */
        UserContainerResponse: {
            user: components["schemas"]["UserContainerResponse.UserResponse"];
        };
        /**
         * HealthCheckDetail
         * @description Individual health check result.
         */
        "ReadinessResponse.HealthCheckDetail": {
            /** Status */
            status: string;
            /**
             * Message
             * @default null
             */
            message: string | null;
        };
        /**
         * ReadinessResponse
         * @description Readiness probe response.
         */
        ReadinessResponse: {
            /**
             * Status
             * @description 'ready' or 'not_ready'
             */
            status: string;
            /** Checks */
            checks: {
                [key: string]: components["schemas"]["ReadinessResponse.HealthCheckDetail"];
            };
            /**
             * Version
             * @default null
             */
            version: string | null;
        };
        HTTPError: {
            detail?: Record<string, never>;
            message?: string;
        };
        /**
         * ModelResponse
         * @description Available model info.
         */
        "ModelsListResponse.ModelResponse": {
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /**
         * ModelsListResponse
         * @description List of available models.
         */
        ModelsListResponse: {
            /** Models */
            models: components["schemas"]["ModelsListResponse.ModelResponse"][];
            /**
             * Default
             * @description Default model ID
             */
            default: string;
        };
        /**
         * HealthResponse
         * @description Liveness probe response.
         */
        HealthResponse: {
            /** Status */
            status: string;
            /**
             * Version
             * @default null
             */
            version: string | null;
        };
        /**
         * VersionResponse
         * @description App version info.
         */
        VersionResponse: {
            /**
             * Version
             * @description App version (JS bundle hash)
             * @default null
             */
            version: string | null;
        };
        /**
         * UserResponse
         * @description User information.
         */
        "AuthResponse.UserResponse": {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Name */
            name: string;
            /**
             * Picture
             * @default null
             */
            picture: string | null;
        };
        /**
         * AuthResponse
         * @description Response from successful authentication.
         */
        AuthResponse: {
            /**
             * Token
             * @description JWT token for subsequent requests
             */
            token: string;
            user: components["schemas"]["AuthResponse.UserResponse"];
        };
        /**
         * MemoryResponse
         * @description Single memory entry.
         */
        "MemoriesListResponse.MemoryResponse": {
            /** Id */
            id: string;
            /** Content */
            content: string;
            /**
             * Category
             * @default null
             */
            category: string | null;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /**
         * MemoriesListResponse
         * @description List of memories.
         */
        MemoriesListResponse: {
            /** Memories */
            memories: components["schemas"]["MemoriesListResponse.MemoryResponse"][];
        };
        /**
         * TokenRefreshResponse
         * @description Response from token refresh.
         */
        TokenRefreshResponse: {
            /**
             * Token
             * @description New JWT token
             */
            token: string;
        };
        /**
         * ClientIdResponse
         * @description Response containing Google Client ID.
         */
        ClientIdResponse: {
            /** Client Id */
            client_id: string;
        };
        /**
         * ConversationResponse
         * @description Conversation summary (without messages).
         */
        "ConversationsListPaginatedResponse.ConversationResponse": {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Model */
            model: string;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /**
             * Message Count
             * @default null
             */
            message_count: number | null;
        };
        /**
         * ConversationsPaginationResponse
         * @description Pagination info for conversations list.
         */
        "ConversationsListPaginatedResponse.ConversationsPaginationResponse": {
            /**
             * Next Cursor
             * @description Cursor for fetching next page (null if no more)
             * @default null
             */
            next_cursor: string | null;
            /**
             * Has More
             * @description Whether there are more pages
             */
            has_more: boolean;
            /**
             * Total Count
             * @description Total number of conversations
             */
            total_count: number;
        };
        /**
         * ConversationsListPaginatedResponse
         * @description Paginated list of conversations.
         */
        ConversationsListPaginatedResponse: {
            /** Conversations */
            conversations: components["schemas"]["ConversationsListPaginatedResponse.ConversationResponse"][];
            pagination: components["schemas"]["ConversationsListPaginatedResponse.ConversationsPaginationResponse"];
        };
        /**
         * ConversationResponse
         * @description Conversation summary (without messages).
         */
        ConversationResponse: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Model */
            model: string;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /**
             * Message Count
             * @default null
             */
            message_count: number | null;
        };
        /**
         * UploadConfigResponse
         * @description File upload configuration.
         */
        UploadConfigResponse: {
            /**
             * Maxfilesize
             * @description Maximum file size in bytes
             */
            maxFileSize: number;
            /**
             * Maxfilespermessage
             * @description Maximum files per message
             */
            maxFilesPerMessage: number;
            /**
             * Allowedfiletypes
             * @description Allowed MIME types
             */
            allowedFileTypes: string[];
        };
        /**
         * UserSettingsResponse
         * @description User settings.
         */
        UserSettingsResponse: {
            /**
             * Custom Instructions
             * @description Custom instructions for the AI
             * @default
             */
            custom_instructions: string;
        };
        /**
         * StatusResponse
         * @description Simple status response for operations that don't return data.
         */
        StatusResponse: {
            /**
             * Status
             * @description Operation status (e.g., 'updated', 'deleted')
             */
            status: string;
        };
        /**
         * SyncConversationResponse
         * @description Conversation summary for sync endpoint.
         */
        "SyncResponse.SyncConversationResponse": {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Model */
            model: string;
            /** Updated At */
            updated_at: string;
            /** Message Count */
            message_count: number;
        };
        /**
         * SyncResponse
         * @description Response from sync endpoint.
         */
        SyncResponse: {
            /** Conversations */
            conversations: components["schemas"]["SyncResponse.SyncConversationResponse"][];
            /**
             * Server Time
             * @description ISO timestamp to use for next sync
             */
            server_time: string;
            /** Is Full Sync */
            is_full_sync: boolean;
        };
        /**
         * ModelCostBreakdown
         * @description Cost breakdown by model.
         */
        "MonthlyCostResponse.ModelCostBreakdown": {
            /** Total */
            total: number;
            /** Total Usd */
            total_usd: number;
            /** Message Count */
            message_count: number;
            /** Formatted */
            formatted: string;
        };
        /**
         * MonthlyCostResponse
         * @description Monthly cost for a user.
         */
        MonthlyCostResponse: {
            /** User Id */
            user_id: string;
            /** Year */
            year: number;
            /** Month */
            month: number;
            /** Total Usd */
            total_usd: number;
            /**
             * Total
             * @description Total in display currency
             */
            total: number;
            /** Currency */
            currency: string;
            /** Formatted */
            formatted: string;
            /** Message Count */
            message_count: number;
            /** Breakdown */
            breakdown: {
                [key: string]: components["schemas"]["MonthlyCostResponse.ModelCostBreakdown"];
            };
        };
        /**
         * MonthCostEntry
         * @description Single month in cost history.
         */
        "CostHistoryResponse.MonthCostEntry": {
            /** Year */
            year: number;
            /** Month */
            month: number;
            /** Total Usd */
            total_usd: number;
            /** Total */
            total: number;
            /** Currency */
            currency: string;
            /** Formatted */
            formatted: string;
            /** Message Count */
            message_count: number;
        };
        /**
         * CostHistoryResponse
         * @description Cost history for a user.
         */
        CostHistoryResponse: {
            /** User Id */
            user_id: string;
            /** History */
            history: components["schemas"]["CostHistoryResponse.MonthCostEntry"][];
        };
        /**
         * FileMetadataResponse
         * @description File metadata in message responses (excludes full data for performance).
         */
        "ConversationDetailPaginatedResponse.FileMetadataResponse": {
            /** Name */
            name: string;
            /** Type */
            type: string;
            /**
             * Messageid
             * @default null
             */
            messageId: string | null;
            /**
             * Fileindex
             * @default null
             */
            fileIndex: number | null;
        };
        /**
         * GeneratedImageResponse
         * @description Generated image metadata.
         */
        "ConversationDetailPaginatedResponse.GeneratedImageResponse": {
            /** Prompt */
            prompt: string;
            /**
             * Image Index
             * @default null
             */
            image_index: number | null;
        };
        /**
         * MessageResponse
         * @description Message in a conversation.
         */
        "ConversationDetailPaginatedResponse.MessageResponse": {
            /** Id */
            id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Content */
            content: string;
            /**
             * Files
             * @default null
             */
            files: components["schemas"]["ConversationDetailPaginatedResponse.FileMetadataResponse"][] | null;
            /**
             * Sources
             * @default null
             */
            sources: components["schemas"]["ConversationDetailPaginatedResponse.SourceResponse"][] | null;
            /**
             * Generated Images
             * @default null
             */
            generated_images: components["schemas"]["ConversationDetailPaginatedResponse.GeneratedImageResponse"][] | null;
            /** Created At */
            created_at: string;
        };
        /**
         * MessagesPaginationResponse
         * @description Pagination info for messages list.
         */
        "ConversationDetailPaginatedResponse.MessagesPaginationResponse": {
            /**
             * Older Cursor
             * @description Cursor for fetching older messages (null if at oldest)
             * @default null
             */
            older_cursor: string | null;
            /**
             * Newer Cursor
             * @description Cursor for fetching newer messages (null if at newest)
             * @default null
             */
            newer_cursor: string | null;
            /**
             * Has Older
             * @description Whether there are older messages
             */
            has_older: boolean;
            /**
             * Has Newer
             * @description Whether there are newer messages
             */
            has_newer: boolean;
            /**
             * Total Count
             * @description Total number of messages in conversation
             */
            total_count: number;
        };
        /**
         * SourceResponse
         * @description Web search source citation.
         */
        "ConversationDetailPaginatedResponse.SourceResponse": {
            /** Title */
            title: string;
            /** Url */
            url: string;
        };
        /**
         * ConversationDetailPaginatedResponse
         * @description Full conversation with paginated messages.
         */
        ConversationDetailPaginatedResponse: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Model */
            model: string;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /** Messages */
            messages: components["schemas"]["ConversationDetailPaginatedResponse.MessageResponse"][];
            message_pagination: components["schemas"]["ConversationDetailPaginatedResponse.MessagesPaginationResponse"];
        };
        /**
         * MessageCostResponse
         * @description Cost breakdown for a message.
         */
        MessageCostResponse: {
            /** Message Id */
            message_id: string;
            /** Cost Usd */
            cost_usd: number;
            /**
             * Cost
             * @description Cost in display currency
             */
            cost: number;
            /** Currency */
            currency: string;
            /** Formatted */
            formatted: string;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Model */
            model: string;
            /**
             * Image Generation Cost Usd
             * @default null
             */
            image_generation_cost_usd: number | null;
            /**
             * Image Generation Cost
             * @default null
             */
            image_generation_cost: number | null;
            /**
             * Image Generation Cost Formatted
             * @default null
             */
            image_generation_cost_formatted: string | null;
        };
        /**
         * ConversationCostResponse
         * @description Cost for a conversation.
         */
        ConversationCostResponse: {
            /** Conversation Id */
            conversation_id: string;
            /** Cost Usd */
            cost_usd: number;
            /**
             * Cost
             * @description Cost in display currency
             */
            cost: number;
            /** Currency */
            currency: string;
            /** Formatted */
            formatted: string;
        };
        /**
         * FileMetadataResponse
         * @description File metadata in message responses (excludes full data for performance).
         */
        "MessagesListResponse.FileMetadataResponse": {
            /** Name */
            name: string;
            /** Type */
            type: string;
            /**
             * Messageid
             * @default null
             */
            messageId: string | null;
            /**
             * Fileindex
             * @default null
             */
            fileIndex: number | null;
        };
        /**
         * GeneratedImageResponse
         * @description Generated image metadata.
         */
        "MessagesListResponse.GeneratedImageResponse": {
            /** Prompt */
            prompt: string;
            /**
             * Image Index
             * @default null
             */
            image_index: number | null;
        };
        /**
         * MessageResponse
         * @description Message in a conversation.
         */
        "MessagesListResponse.MessageResponse": {
            /** Id */
            id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Content */
            content: string;
            /**
             * Files
             * @default null
             */
            files: components["schemas"]["MessagesListResponse.FileMetadataResponse"][] | null;
            /**
             * Sources
             * @default null
             */
            sources: components["schemas"]["MessagesListResponse.SourceResponse"][] | null;
            /**
             * Generated Images
             * @default null
             */
            generated_images: components["schemas"]["MessagesListResponse.GeneratedImageResponse"][] | null;
            /** Created At */
            created_at: string;
        };
        /**
         * MessagesPaginationResponse
         * @description Pagination info for messages list.
         */
        "MessagesListResponse.MessagesPaginationResponse": {
            /**
             * Older Cursor
             * @description Cursor for fetching older messages (null if at oldest)
             * @default null
             */
            older_cursor: string | null;
            /**
             * Newer Cursor
             * @description Cursor for fetching newer messages (null if at newest)
             * @default null
             */
            newer_cursor: string | null;
            /**
             * Has Older
             * @description Whether there are older messages
             */
            has_older: boolean;
            /**
             * Has Newer
             * @description Whether there are newer messages
             */
            has_newer: boolean;
            /**
             * Total Count
             * @description Total number of messages in conversation
             */
            total_count: number;
        };
        /**
         * SourceResponse
         * @description Web search source citation.
         */
        "MessagesListResponse.SourceResponse": {
            /** Title */
            title: string;
            /** Url */
            url: string;
        };
        /**
         * MessagesListResponse
         * @description Paginated messages response (for dedicated messages endpoint).
         */
        MessagesListResponse: {
            /** Messages */
            messages: components["schemas"]["MessagesListResponse.MessageResponse"][];
            pagination: components["schemas"]["MessagesListResponse.MessagesPaginationResponse"];
        };
        /**
         * FileMetadataResponse
         * @description File metadata in message responses (excludes full data for performance).
         */
        "ChatBatchResponse.FileMetadataResponse": {
            /** Name */
            name: string;
            /** Type */
            type: string;
            /**
             * Messageid
             * @default null
             */
            messageId: string | null;
            /**
             * Fileindex
             * @default null
             */
            fileIndex: number | null;
        };
        /**
         * GeneratedImageResponse
         * @description Generated image metadata.
         */
        "ChatBatchResponse.GeneratedImageResponse": {
            /** Prompt */
            prompt: string;
            /**
             * Image Index
             * @default null
             */
            image_index: number | null;
        };
        /**
         * SourceResponse
         * @description Web search source citation.
         */
        "ChatBatchResponse.SourceResponse": {
            /** Title */
            title: string;
            /** Url */
            url: string;
        };
        /**
         * ChatBatchResponse
         * @description Response from batch chat endpoint.
         */
        ChatBatchResponse: {
            /** Id */
            id: string;
            /**
             * Role
             * @default assistant
             * @constant
             */
            role: "assistant";
            /** Content */
            content: string;
            /**
             * Files
             * @default null
             */
            files: components["schemas"]["ChatBatchResponse.FileMetadataResponse"][] | null;
            /**
             * Sources
             * @default null
             */
            sources: components["schemas"]["ChatBatchResponse.SourceResponse"][] | null;
            /**
             * Generated Images
             * @default null
             */
            generated_images: components["schemas"]["ChatBatchResponse.GeneratedImageResponse"][] | null;
            /** Created At */
            created_at: string;
            /**
             * Title
             * @description Auto-generated conversation title (first message only)
             * @default null
             */
            title: string | null;
            /**
             * User Message Id
             * @description Real ID of the user message (for updating temp IDs in frontend)
             * @default null
             */
            user_message_id: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
